name: CI

on: [push]

jobs:
  build-win:

    runs-on: windows-2016
    
    steps:
      - uses: actions/checkout@v1
      - name: Build on windows
        run: open_window\shell.bat && build.bat          
        shell: cmd

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build on ubuntu
        run: |
          sudo apt-get install libsdl2-dev
          g++ open_window/main.cpp -w -lSDL2 -o main

  build-macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build on macOS
        run: |
          tar -zxvf SDL2-2.0.10.tar.gz
          ./configure --prefix=/home/user/SDL && make && make install
          g++ open_window/main.cpp -o main `/home/user/SDL/sdl-config --cflags --libs` -framework OpenGL -framework Cocoa