name: CI

on: [push]

jobs:
#   build-win:

#     runs-on: windows-2016
    
#     steps:
#       - uses: actions/checkout@v1
#       - name: Build on windows
#         run: open_window\shell.bat && build.bat          
#         shell: cmd

#   build-ubuntu:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Build on ubuntu
#         run: |
#           sudo apt-get install libsdl2-dev
#           g++ open_window/main.cpp -w -lSDL2 -o main

  build-macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build on macOS
        run: |
          brew install SDL2 && \
          cp /usr/local/Cellar/SDL2/2.0.10/include ./open_window/include && \
          cp /usr/local/Cellar/SDL2/2.0.10/lib ./open_window/lib && \
          g++ open_window/main.cpp -o open_window/main -I open_window/include -L open_window/lib -l SDL2-2.0.0
          # tar -zxvf SDL2-2.0.10.tar.gz && cd SDL2-2.0.10 && sudo mkdir /home/user && \
          # ./configure --prefix=/home/user/SDL && make && sudo make install && cd .. && \
          # g++ open_window/main.cpp -o main `/home/user/SDL/sdl-config --cflags --libs` -framework OpenGL -framework Cocoa
