name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2016
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: open_window/shell.bat
    - name: Run build
      run: open_window/build.bat
