name: CI

on: [push]

jobs:
  build-win:

    runs-on: windows-2016
    
    steps:
      - uses: actions/checkout@v1
      - name: Build on windows
        run: open_window\shell.bat && build.bat          
        shell: cmd

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build on ubuntu
        run: |
          sudo apt-get install libsdl2-dev && \
          g++ open_window/main.cpp -w -lSDL2 -o main

  build-macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build on macOS
        run: |
          brew install SDL2 && \
          mkdir ./open_window/include/ && cp -R /usr/local/Cellar/SDL2/2.0.10/include ./open_window/include && \
          mkdir ./open_window/lib/ && cp -R /usr/local/Cellar/SDL2/2.0.10/lib ./open_window/lib && \
          g++ ./open_window/main.cpp -o ./open_window/main -I ./open_window/include -L ./open_window/lib -l SDL2-2.0.0 && \
          ls -l open_window